application: iceotter
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /pages
  script: juliating.application

- url: /
  upload: staticPages/index.html
  static_files: staticPages/index.html

- url: /images
  static_dir: images
- url: /images/headers
  static_dir: images/headers

- url: /stylesheets
  static_dir: stylesheets

- url: /about
  upload: staticPages/about.html
  static_files: staticPages/about.html

- url: /inquire
  upload: staticPages/contact.html
  static_files: staticPages/contact.html

- url: /ultimate
  upload: staticPages/ultimate.html
  static_files: staticPages/ultimate.html

- url: /log
  upload: staticPages/log.html
  static_files: staticPages/log.html

- url: /terminal
  upload: staticPages/terminal.html
  static_files: staticPages/terminal.html

- url: /inspect
  upload: staticPages/resume.html
  static_files: staticPages/resume.html

- url: /notebook
  upload: staticPages/notebook.html
  static_files: staticPages/notebook.html

- url: /gallery
  upload: staticPages/gallery.html
  static_files: staticPages/gallery.html

- url: /.*
  upload: staticPages/index.html
  static_files: staticPages/index.html
